spring.datasource.url=jdbc:h2:mem:testdb
# Configurações para desenvolvimento (H2 em memória)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
# Desativa o Redis temporariamente para não dar erro sem o container
spring.cache.type=none 

# Habilita e configura o Redis para caching (exemplo, ajuste conforme seu ambiente Redis)
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
